Move unit testing to local
ESE-Peasy/PosturePerfection pull request #54
Opened 2021-02-24 14:11 UTC by miklasr

# Details

- Unit testing will now be done locally
- There is a new `./test.sh` script to run tests locally
- README has been updated accordingly

# Checklist

## Code
- [ ] I have added some tests
- [ ] I have run the tests locally to ensure they all pass

## Documentation
- [ ] I have updated documentation appropriately (README)

2021-02-24 17:38 UTC, C-Begley approved these changes
Bit of a pain to have to count on anyone to run tests themselves, but I know we've been advised to use github actions less.

2021-02-24 17:46 UTC, C-Begley requested changes
Currently getting issue No Tests were found

2021-02-24 19:24 UTC, C-Begley approved these changes
Tests now pass on my local machine, happy to merge

2021-02-25 08:44 UTC, Ashwin-MJ approved these changes
Tests run on my machine too. Nice work Miklas!

2021-02-25 08:48 UTC, merged